### ISSUE TITLE
Invariant Violation: Native module cannot be null

### ISSUE THREAD

**Issue by hopewise** [react-native-community/react-native-push-notification-ios#43]
At iOS, it builds successfully, however, when the app starts, I get this error:

```

Invariant Violation: Native module cannot be null.

constructor
    NativeEventEmitter.js:36:6
<global>
    PushNotificationIOS.js:17:32
loadModuleImplementation
    require.js:321:4
guardedLoadModule
    require.js:210:11
metroRequire
    require.js:128:6
module.exports.get__PushNotificationIOS
    react-native-implementation.js:257:11
<global>
    index.ios.js:10:13
loadModuleImplementation
    require.js:321:4
guardedLoadModule
    require.js:210:11


```

Any idea?

**Comment by hopewise** [comment]
this has been solved, but now I got this issue: https://github.com/react-native-community/react-native-push-notification-ios/issues/44

**Comment by rjshoemaker55** [comment]
How did you fix this?

**Comment by hopewise** [comment]
I manually linked the library, it seems its wasn't linked correctly, just followed docs on manually linking it.. but I am stuck at #44 😞 it seems I will implement the iOS notifications natively..

**Comment by hopewise** [comment]
The problem is not solved yet..

**Comment by hopewise** [comment]
I was using version `v3.1.2 ` of `react-native-push-notification` which depends on outdated `PushNotificationIOS`, installing `react-native-push-notification` from main stream fixed my issue.

`react-native-push-notification` needs to create a new release to have this important commit: https://github.com/zo0r/react-native-push-notification/commit/5b02761d927cdacdc50fde41d58506f64d8154aa

**Comment by preetb123** [comment]
I am getting this same issue. not working even after installing from mainstream.

**Comment by hopewise** [comment]
Sometimes, closing XCode and open in again would solve the issue.

**Comment by schumannd** [comment]
@hopewise can you please open this again? I am still experiencing this issue


    "react": "16.9.0",
    "react-native": "0.61.4",
    "@react-native-community/push-notification-ios": "1.0.3",

**Comment by hopewise** [comment]
@schumannd opened..

**Comment by radetsky** [comment]
Something is very simple. 
@react-native-community/push-notification-ios": "1.0.3" linked with Podfile after install and link commands.
Just cd to ios/ and run 'pod install'. 
And restart the project.

**Comment by schumannd** [comment]
@radetsky that is exactly what I did and it resulted in this error message.

**Comment by leonardomarciano** [comment]
+1 Same error here.

**Comment by Jmzp** [comment]
+1 Same error here. **React Native** 0.61.5

**Comment by Jmzp** [comment]
In my case I solved this changing

`import {  PushNotificationIOS } from 'react-native';`

to 

`import PushNotificationIOS from '@react-native-community/push-notification-ios';`

because I use this flag

`notification.finish(PushNotificationIOS.FetchResult.NoData);`

**Comment by goodryanboy** [comment]
+1 Same error here. react-native 0.61.4

**Comment by Asleepace** [comment]
+1 Same error here on react-native `0.61.5`

**Comment by manish-jain-1** [comment]
Same error here with RN 59.10. I have patched above zo0r/react-native-push-notification@5b02761 manually. All code/setup steps in RN/XCode completed as per https://facebook.github.io/react-native/docs/pushnotificationios but no luck. Any ideas?

**Comment by Wout-Vanneste-student** [comment]
Hi! I'm having the same issue. BUT I know what is the cause, it's the package `react-navigation-stack` or `react-navigation-tabs`. They both use the package `react-native-reanimated` which is creating the following error for me.

![image](https://user-images.githubusercontent.com/44393610/70377152-5803bd80-1911-11ea-8623-cd52f2609e81.png)

I have tried everything that all of you already posted before me. And none of them have worked successfully, unfortunately...

If anyone has any idea how to fix this issue. You would really help me out big time.

**Comment by manish-jain-1** [comment]
So, here's the solution that worked for me for Xcode legacy build systems: remove react-native core IOS xcodeproj project from libraries, also, remove one that comes with react-native-push-notification (Push notification manager something) and add new XCodeProj file from this iOS project from below node_modules path. Also add path to Xcode > build settings > header search path > add $(SRCROOT)/../node_modules/@react-native-community/push-notification-ios/ios (non-recursive)

Path for XCodeproj - $(SRCROOT)/../node_modules/@react-native-community/push-notification-ios/ios

<img width="309" alt="image" src="https://user-images.githubusercontent.com/1090670/70753480-b356f680-1ce9-11ea-8b8e-9f6914fcce26.png">

**Comment by chentianci123** [comment]
Hello, have you solved it?

**Comment by chentianci123** [comment]
> +1 Same error here on react-native `0.61.5`
Hello, have you solved it?

**Comment by gagandeep-s** [comment]
same error here 0.61.5

**Comment by bettimms** [comment]
I got the same issue as @Wout-Vanneste-student  described. https://github.com/react-native-community/react-native-push-notification-ios/issues/43#issuecomment-562862506

This is how it worked for me; After I installed these libraries(described in the post in the link above) through `yarn` i had to do also `pod install` and it worked.

**Comment by tomthornton** [comment]
Same problem here. 0.61.5

**Comment by massoprod** [comment]
The same problem also 0.61.5 react-native version

**Comment by rnnyrk** [comment]
Same issue on 0.61.5. Can't figure out which package it is or how to debug this. Any suggestions?

**Comment by Naturalclar** [comment]
For those who are having trouble getting this module on 0.61.5, please run `pod install` in your `ios` folder.

**Comment by inmaSecret** [comment]
ok, my solution was:
I had an old version 0.59 and now I have 0.61.5
I used react-native-push-notification for both platforms
my solution was
1. remove the package, yarn remove react-native-push-notification
2. delete last code in xcode appdelegate.m

```
/*#import <React/RCTPushNotificationManager.h>*/ - //here

#import <UserNotifications/UserNotifications.h>

@implementation AppDelegate

 /*- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
 {
  [RCTPushNotificationManager didRegisterUserNotificationSettings:notificationSettings];
 }
 // Required for the register event.
 - (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
 {
  [RCTPushNotificationManager didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
 }
 // Required for the notification event. You must call the completion handler after handling the remote notification.
 - (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
                                                        fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
 {
   [RCTPushNotificationManager didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
 }
 // Required for the registrationError event.
 - (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
 {
  [RCTPushNotificationManager didFailToRegisterForRemoteNotificationsWithError:error];
 }
 // Required for the localNotification event.
 - (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
 {
  [RCTPushNotificationManager didReceiveLocalNotification:notification];
 }*/ - //here

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"diarydetox"
                                            initialProperties:nil];
```
3. install again, yarn add react-native-push-notification
4. add in pod file this line
`   pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios/RNCPushNotificationIOS.podspec'`
5. cd ios/ && pod install
clear package and build in xcode again
it works for me ;)

**Comment by ErtugrulBEKTIK** [comment]
Same problem here. 0.59.8

**Comment by nabeelItilite** [comment]
@inmaSecret is this code working for u in ios?
For me notification is not showing, but working fine in android

**Comment by inmaSecret** [comment]
> @inmaSecret is this code working for u in ios?
> For me notification is not showing, but working fine in android

the block code in xcode appdelegate.m related to pushNotification should be removed. my problem was  that the appdelegate code left old RCTPushNotificationManager functionality after delete this I could fix the problem. 
Could you solve your problem with my solution finally?, it works for me in both

**Comment by nabeelItilite** [comment]
@inmaSecret thanks, it worked for me. but still issue with getting messages while app in background in ios

**Comment by Ryan113** [comment]
I am getting this issue as well. Unfortunately, none of the above solutions have worked for me.

**Comment by FiveX-dev** [comment]
After "cd ios/ && pod install" you should rebuild your project.

**Comment by raimonkh** [comment]
So solved this by adding manually `@react-native-community/push-notification-ios` tho it should be a dependency

**Comment by manojeeva** [comment]
For me, I've created a new project, added this only dependency. First, the build is working fine. then added react-native-notifications. Then this error started showing. **The cleaning build folder solved the issue.** 
Also adding react-native-notifications to the project. 
PushNotificationIOS.presentLocalNotification(details); is no more showing the notification. Any idea why this issue?

**Comment by petermirmo** [comment]
Nothing here as worked for me :(

**Comment by petermirmo** [comment]
> @react-native-community/push-notification-ios

This did not work for me at first. I had to: 
1. delete node_modules & packeage-lock.json
2. npm cache clean --force
3. npm install --save @react-native-community/push-notification-ios

**Comment by ashokrajbathu** [comment]
After a long frustrating period, I decided to understand what does it mean actually. As far as I understand it is trying to tell that some npm package is identified in your node modules and it's not just enough to install the package but you have to add some code in ios inorder to make that package works.

In my case I have installed npm package of react-native-push-notifications and done all the required changes in android but not in IOS. my ios app which used to work fine suddenly started giving me this clueless error. Finally, I have solved it. thanks to everyone.

**Comment by Taenerys** [comment]
Hey guys, I'm also facing the same error with React Native 0.62.2!

I managed to build the app successfully after running "pod install" in iOS folder, but when the app starts I got this error. Everyone here seems to know what their bug is coming from (such as libraries, dependencies, etc.). But here looking at the error message I couldn't find a clue of where the bug potentially is from. If anyone could point me to the right direction, I'd be very very thankful!

```
Invariant Violation: Native module cannot be null.

invariant
    browser.js:38:14
constructor
    NativeEventEmitter.js:37:15
<global>
    index.js:18:32
loadModuleImplementation
    require.js:321:11
<global>
    index.ios.js:4
loadModuleImplementation
    require.js:321:11
<global>
    index.js:7:38
loadModuleImplementation
    require.js:321:11
<global>
    NotificationService.js:2
loadModuleImplementation
    require.js:321:11
<global>
    Login.js:15
loadModuleImplementation
    require.js:321:11
<global>
    Login.js:3
loadModuleImplementation
    require.js:321:11
<global>
    Navigation.js:5
loadModuleImplementation
    require.js:321:11
<global>
    App.js:6
loadModuleImplementation
    require.js:321:11
<global>
    index.js:6
loadModuleImplementation
    require.js:321:11
<global>
    index.js:6
loadModuleImplementation
    require.js:321:11
guardedLoadModule
    require.js:201:44
global code
    index.bundle?platform=ios&dev=true&minify=false:173228:3
```

**Comment by TheMrugraj** [comment]
In My case, I commented the `use_native_modules!` by mistake and that's why some of the node modules having podspecs where not getting installed and was the real culprit. I just uncommented it and then `pod install`. It worked!

**Comment by netpoe** [comment]
Any updates with this one?

Environment:

- `"expo": "^37.0.0",`
- `"expo-notifications": "~0.1.1",`

I'm getting this error when using `expo-notifications` as described in the [expo-documentation](https://docs.expo.io/versions/latest/sdk/notifications/#setbadgecountasyncbadgecount-number-options-setbadgecountoptions-promiseboolean): 

<img width="376" alt="Screen Shot 2020-07-03 at 00 05 52" src="https://user-images.githubusercontent.com/4053518/86437089-f6e27380-bcc0-11ea-9002-2a3817ad6392.png">

I'm using a managed workflow. This happens in iOS Simulator iPhone 8. Could it be that it's because I'm at the simulator?
This error won't happen in an Android device running the same app. 

The code that's causing this is: 

```
React.useEffect(() => {
    Notifications.setBadgeCountAsync(2);
  }, [pendingPaymentRequestsCount]);
```

What I do get in Android is this warning: 

![photo_2020-07-03_00-09-35](https://user-images.githubusercontent.com/4053518/86437309-812ad780-bcc1-11ea-9a52-e95cd1692610.jpg)

**Comment by jozeperez** [comment]
I too am having the same issue  as @netpoe. I have tried both "expo-notifications": "~0.1.1" and "expo-notifications": "^0.4.0". I'm currently using "expo": "~37.0.3". As soon as I add "**import * as Notifications from 'expo-notifications';**" to a file the app won't load on iOS simulator.

I guess we are all waiting for updates on this one =/

**Comment by guanw** [comment]
FYI, for folks who are having issue using expo + expo-notifications. It seems like the lib is not ready for use yet.

https://github.com/expo/expo/tree/master/packages/expo-notifications#installation-in-managed-expo-projects

**Comment by brunoaduarte** [comment]
I was having the same issues here after adding 'expo-notifications' to my project.

I fixed by creating a brand new blank project using latest version of expo, copying the files from old project and reinstalling extensions one by one as the compilation errors were presented. The first i've installed was 'expo-notifications' btw.

If you want to make sure 'expo-notifications' is working just create the new project, install this dependency and copy the App.js content from the example

https://docs.expo.io/versions/latest/sdk/notifications/

Only then migrate the files from your old project.

**Comment by Naturalclar** [comment]
expo-notifications is a separate package from this repository.
For any issues regarding the expo-notification package, please use the issue tracker for the [expo-notification repository](https://github.com/expo/expo/tree/master/packages/expo-notifications)

**Comment by edijs1984** [comment]
for existing project i use ..   import  {Notifications}  from "expo";

**Comment by Ro4z** [comment]
I just run `npx pod-install ios` in root of project, and re-build iOS. it works for me!

**Comment by ghasemikasra39** [comment]
I am only getting this error when running my test:
```
yarn run v1.22.4
$ jest __tests__/App1.test.tsx
 FAIL  __tests__/App1.test.tsx
  ● Test suite failed to run

    Invariant Violation: Native module cannot be null.

      1 | import { createSlice, PayloadAction } from '@reduxjs/toolkit';
      2 | import { BackendNotificationInterface } from '../../services/api/PushNotificationSubscriber';
    > 3 | import PushNotificationIOS from '@react-native-community/push-notification-ios';
        | ^
      4 |
      5 | export interface StoredNotificationInterface {
      6 |   id: number;

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:37:7)
      at Object.<anonymous> (node_modules/@react-native-community/push-notification-ios/js/index.js:18:33)
      at Object.<anonymous> (src/store/slices/NotificationsSlice.ts:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        32.126s
Ran all test suites matching /__tests__\/App1.test.tsx/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Any solution to this?

**Comment by RicardoBrito1938** [comment]
a tried to mock, but i am also getting this error when i run Jest, anyone could fix it?

**Comment by Naveen562117** [comment]
hi @amit13091992 did you make any progress on this or any solution did you find on this so far

**Comment by Naveen562117** [comment]
have same problem no clue which package causing this issue

**Comment by metrue** [comment]
> a tried to mock, but i am also getting this error when i run Jest, anyone could fix it?

Got the same issue
```
Invariant Violation: Native module cannot be null.

      1 | import Notifications from '../types/notifications'
    > 2 | import PushNotificationIOS from '@react-native-community/push-notification-ios'
        | ^
      3 | 
      4 | export const check = () => {
      5 |   return async (dispatch) => {

```

**Comment by Naveen562117** [comment]
hi @metrue ,, I am able to solve this error by removing google play referral , and installed some other package to get the work done

you have to go though package by package and remove them and add them this is the only way to trouble shoot this error after spending weeks on this was able to solve this & try this once - 
 yarn add @react-native-community/push-notification-ios

**Comment by metrue** [comment]
Thanks, @Naveen562117 

It magically disappeared after I ran `pod install`.

**Comment by Maddumage** [comment]
I also faced the same issue.
"react-native": "0.63.4"
"@react-native-community/push-notification-ios": "^1.8.0"
"react-native-push-notification": "^7.0.0"
The above fixes did not work for me. 
Any ideas, Please help.

**Comment by mohadel92** [comment]
same ugly issue

**Comment by Mediacannibal** [comment]
> same ugly issue

hi, the only way to troubleshoot this issue is to , remove the packages and its dependency one by one by commenting the code and check for the package  which is causing the issue in my case it was some other react-native package and have spent over week on this , so please go though package by package and trouble shoot

**Comment by jSkrills** [comment]
> > a tried to mock, but i am also getting this error when i run Jest, anyone could fix it?
> 
> Got the same issue
> 
> ```
> Invariant Violation: Native module cannot be null.
> 
>       1 | import Notifications from '../types/notifications'
>     > 2 | import PushNotificationIOS from '@react-native-community/push-notification-ios'
>         | ^
>       3 | 
>       4 | export const check = () => {
>       5 |   return async (dispatch) => {
> ```

I also see this same issue.

**Comment by rusakovic** [comment]
> I am only getting this error when running my test:
> 
> ```
> yarn run v1.22.4
> $ jest __tests__/App1.test.tsx
>  FAIL  __tests__/App1.test.tsx
>   ● Test suite failed to run
> 
>     Invariant Violation: Native module cannot be null.
> 
>       1 | import { createSlice, PayloadAction } from '@reduxjs/toolkit';
>       2 | import { BackendNotificationInterface } from '../../services/api/PushNotificationSubscriber';
>     > 3 | import PushNotificationIOS from '@react-native-community/push-notification-ios';
>         | ^
>       4 |
>       5 | export interface StoredNotificationInterface {
>       6 |   id: number;
> 
>       at invariant (node_modules/invariant/invariant.js:40:15)
>       at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:37:7)
>       at Object.<anonymous> (node_modules/@react-native-community/push-notification-ios/js/index.js:18:33)
>       at Object.<anonymous> (src/store/slices/NotificationsSlice.ts:3:1)
> 
> Test Suites: 1 failed, 1 total
> Tests:       0 total
> Snapshots:   0 total
> Time:        32.126s
> Ran all test suites matching /__tests__\/App1.test.tsx/i.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> Any solution to this?

Confirm. Have the same issue

**Comment by MrIceman** [comment]
If you're using Expo then use this to request notification permissions instead

```
import * as Notifications from 'expo-notifications';

export async function requestUserPermission() {
    let status = await Notifications.getPermissionsAsync()
    if (status.status !== "granted") {
        await Notifications.requestPermissionsAsync()
    }
}

```

**Comment by Raymond-Cox** [comment]
Fixed this issue today with the following:

```
jest.mock('@react-native-community/push-notification-ios', () => ({
    addEventListener: jest.fn(),
    requestPermissions: jest.fn(),
  }));
  ```
  
  It's weird, you can comment out the return objects `addEventListener` and `requestPermissions` assignment and it continues to work, but if you try the following it doesn't:
  
  ```
  jest.mock('@react-native-community/push-notification-ios');
  ```
  
  Add it to your jest setup file and never worry about it again.

**Comment by edgarilb** [comment]
> Hey guys, I'm also facing the same error with React Native 0.62.2!
> 
> I managed to build the app successfully after running "pod install" in iOS folder, but when the app starts I got this error. Everyone here seems to know what their bug is coming from (such as libraries, dependencies, etc.). But here looking at the error message I couldn't find a clue of where the bug potentially is from. If anyone could point me to the right direction, I'd be very very thankful!
> 
> ```
> Invariant Violation: Native module cannot be null.
> 
> invariant
>     browser.js:38:14
> constructor
>     NativeEventEmitter.js:37:15
> <global>
>     index.js:18:32
> loadModuleImplementation
>     require.js:321:11
> <global>
>     index.ios.js:4
> loadModuleImplementation
>     require.js:321:11
> <global>
>     index.js:7:38
> loadModuleImplementation
>     require.js:321:11
> <global>
>     NotificationService.js:2
> loadModuleImplementation
>     require.js:321:11
> <global>
>     Login.js:15
> loadModuleImplementation
>     require.js:321:11
> <global>
>     Login.js:3
> loadModuleImplementation
>     require.js:321:11
> <global>
>     Navigation.js:5
> loadModuleImplementation
>     require.js:321:11
> <global>
>     App.js:6
> loadModuleImplementation
>     require.js:321:11
> <global>
>     index.js:6
> loadModuleImplementation
>     require.js:321:11
> <global>
>     index.js:6
> loadModuleImplementation
>     require.js:321:11
> guardedLoadModule
>     require.js:201:44
> global code
>     index.bundle?platform=ios&dev=true&minify=false:173228:3
> ```

I am getting the exact same error. Can you please share how did you fix it?

**Comment by SuhailBt** [comment]
Getting same issue. Nothing mentioned above is working.

"react-native": "~0.63.3"

Adding screenshot


Invariant Violation: Native module cannot be null.


<img width="381" alt="Screenshot 2021-07-07 at 7 17 44 PM" src="https://user-images.githubusercontent.com/65166275/124770705-2e30d380-df58-11eb-9026-424cefcdcfba.png">

**Comment by edgarilb** [comment]
> Getting same issue. Nothing mentioned above is working.
> 
> 
> 
> "react-native": "~0.63.3"
> 
> 
> 
> Adding screenshot
> 
> 
> 
> 
> 
> Invariant Violation: Native module cannot be null.
> 
> 
> 
> 
> 
> <img width="381" alt="Screenshot 2021-07-07 at 7 17 44 PM" src="https://user-images.githubusercontent.com/65166275/124770705-2e30d380-df58-11eb-9026-424cefcdcfba.png">
> 
> 

I am using Expo - managed workflow and the problem was solved when I upgraded to expo SDK 40.0.0. I am assuming that some node_module dependencies were not supported by managed work flow from Expo at 38 or 39 versions. It is kind of random, but I have the application running fine again.

**Comment by SuhailBt** [comment]
Mine is ejected one. I was using expo then ejected. Working fine for android but not for iOS

**Comment by abdul-qadir117** [comment]
Any luck finding the solution? I have same issue but I am not even using push notifications

**Comment by pckz** [comment]
any news about this issue? I have a project ejected that I updated from expo 39 to 43 and in IOS I receive this error. Android works well :(

**Comment by ivanichi** [comment]
i got the same problem. RN. 0.63.4.
"@react-native-community/push-notification-ios": "^1.10.1",
"react-native-push-notification": "^8.1.1"
